### ISSUE TITLE
how do you run code for video 

### ISSUE THREAD

**Issue by Umeshkumar27101998** [divya21raj/Actor-Recognition-In-Movies#1]
how do you get video to run code for face recognization in a video.  
in my code i have following error.
No output of video is opened and nothing happend after executing code for face recognization in a video.
![issue](https://user-images.githubusercontent.com/31234824/73047781-ef5ea900-3e9c-11ea-88f0-0b5acd7e1bb6.JPG)

**Comment by LeoLee321** [comment]
i have the same problem

**Comment by divya21raj** [comment]
> i have the same problem

Do you have the files in the folders mentioned in the command you're running?
