### ISSUE TITLE
HTTPError in access

### ISSUE THREAD

**Issue by meenakshi2003** [divya21raj/Actor-Recognition-In-Movies#2]
Traceback (most recent call last):
File "getData.py", line 34, in <module>
search.raise_for_status()
File "C:\Users\MeenakshiAnnamalai\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: PermissionDenied for url: https://api.cognitive.microsoft.com/bing/v7.0/images/search?q=surya+sivakumar&offset=0&count=50

**Comment by divya21raj** [comment]
Make sure to get your own Bing search API key from [here](https://azure.microsoft.com/en-us/try/cognitive-services/?api=bing-image-search-api) and fill it up in the code.
